# Name the workflow
name: Tag unassigned issues

# Define the event that triggers the workflow
on:
  # Run the workflow every 5 minutes
  workflow_dispatch:

# Define the job that the workflow will run
jobs:
  tag-issues:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install PowerShell
        run: |
          sudo snap install powershell --classic


      - name: Verify GitHub CLI is installed
        run: gh --version
      
      
      # Retrieve a list of issues and parse them as JSON
      # Loop through the list of issues and tag them as necessary
      - name: Tag issues
        shell: pwsh
        run: |
          $time_threshold = [DateTime]::UtcNow.AddMinutes(-6).ToString("o")
          $blocker_tag = "blocker"
          $non_blocker_tag = "non-blocker"
          $ignored_tag = "type-repo_work"

          gh issue list --json number,labels,assignees > issues.json
        
          # Parse the JSON file using PowerShell and print the labels and assignees of each issue
          $issues = Get-Content issues.json | ConvertFrom-Json
          foreach ($issue in $issues) {
            Write-Host "Issue #$($issue.number):"
            Write-Host "  Labels: $($issue.labels.name -join ', ')"
            Write-Host "  Assignees: $($issue.assignees.login -join ', ')"
          }