# Name the workflow
name: Tag unassigned issues

# Define the event that triggers the workflow
on:
  # Run the workflow every 5 minutes
  workflow_dispatch:

env:
  GH_TOKEN: ${{ github.token }}

# Define the job that the workflow will run
jobs:
  tag-issues:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install PowerShell
        run: |
          sudo snap install powershell --classic

      - name: Verify GitHub CLI is installed
        run: gh --version

      - name: Tag issues
        shell: pwsh
        run: |
          $time_threshold_blocker = [DateTime]::UtcNow.AddMinutes(-6).ToString("o")
          $time_threshold_non_blocker = [DateTime]::UtcNow.AddMinutes(-20).ToString("o")
          $blocker_tag = "blocking"
          $non_blocker_tag = "Non-Blocking"
          $ignored_tag = "type-repo_work"
          $out_tte_tag = "out-tte"

          # Get the list of issues
          gh issue list --json number,labels,assignees,createdAt > issues.json
          
          # Parse the JSON file using PowerShell and print the labels and assignees of each issue
          $issues = Get-Content issues.json | ConvertFrom-Json
          echo "Found $($issues.Count) issues"

          # Iterate over all the repo issues
          foreach ($issue in $issues) {
            
            # If the issue has no tags, add the non_blocker_tag
            if (-not ($issue.labels.Count -gt 0)) {
              echo "Found issue $($issue.number) have no tags adding it."
              gh issue edit $issue.number --add-label $non_blocker_tag
            }

            if ($ignored_tag, $out_tte_tag -notin $issue_labels -and (-not $issue.assignee)) {
              echo "Found issue $($issue.number) with no ignore label and with no out tte label also with no assignee"
              if ($issue.labels.Contains($blocker_tag)) {
                if ([DateTime]::Parse($issue.createdAt) -lt $time_threshold_blocker) {
                  gh issue edit $issue.number --add-label $out_tte_tag
                }
              } else {
                if ([DateTime]::Parse($issue.createdAt) -lt $time_threshold_non_blocker) {
                  gh issue edit $issue.number --add-label $out_tte_tag
                }
              }
            }
          }