name: Tag unassigned issues

# Define the event that triggers the workflow
on:
  workflow_dispatch:
    # Run the workflow every hour

env:
  # Set the value of the GH_TOKEN environment variable to the token associated with the GitHub App used to run the workflow
  GH_TOKEN: ${{ github.token }}

# Define the job that the workflow will run
jobs:
  tag-issues:
    runs-on: ubuntu-latest
    
    # Allow the workflow to modify issues in the repository
    permissions:
      issues: write

    steps:

      # Tag issues based on their labels, assignees, and creation time
      - name: Tag issues
        shell: pwsh
        run: |
          # Set the time thresholds and tag names
          $time_threshold_blocker = [DateTime]::UtcNow.AddHours(-24).ToString("o")
          $time_threshold_non_blocker = [DateTime]::UtcNow.AddHours(-48).ToString("o")
          $blocker_tag = "blocking"
          $ignored_tag = "type-repo_work"
          $out_tte_tag = "out-tte"

          echo "REPO ${$GITHUB_REPOSITORY}"

          # Get the list of issues and save it to a JSON file.
          #Filter to get onl open issues with no assignee and without specific labels
          gh issue list --json number,labels,assignees,createdAt  --search "is:open no:assignee -label:out-tte -label:type-repo_work" --repo $GITHUB_REPOSITORY > issues.json 
          
          # Parse the JSON file using PowerShell and print the labels and assignees of each issue
          $issues = Get-Content issues.json | ConvertFrom-Json
          echo "Found $($issues.Count) issues"

          # Iterate over all the repo issues
          foreach ($issue in $issues) {
            # Check if the issue has the ignored tag or the out tte tag, and has no assignee
            if (-not $issue.assignees) {
              if ($issue.labels -like $blocker_tag) {
                if ([DateTime]::Parse($issue.createdAt) -lt $time_threshold_blocker) {
                  # Add the out tte tag to the issue if it is a blocker and has been open for more than 24 hours
                  gh issue edit $issue.number --add-label $out_tte_tag
                }
              } else {
                if ([DateTime]::Parse($issue.createdAt) -lt $time_threshold_non_blocker) {
                  # Add the out tte tag to the issue if it is not a blocker and has been open for more than 48 hours
                  gh issue edit $issue.number --add-label $out_tte_tag
                }
              }
            }
          }