# Name the workflow
name: Tag unassigned issues

# Define the event that triggers the workflow
on:
  # Run the workflow every 5 minutes
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

# Define the job that the workflow will run
jobs:
  tag-issues:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install PowerShell
        run: |
          sudo snap install powershell --classic


      - name: Verify GitHub CLI is installed
        run: gh --version
      # Step 3: Check for unassigned issues
      - name: Check for unassigned issues
        run: |
          # Get all open issues that are not assigned to anyone and not labeled as 'type-repo_work'
          $issues = gh issue list --state open --assignee none --label -type-repo_work --json number,title,labels,url,created_at | jq -c '.[]'

          # Loop through each unassigned issue
          foreach ($issue in $issues) {
            # Parse the issue object from JSON and extract relevant properties
            $issue_object = $issue | ConvertFrom-Json
            $issue_number = $issue_object.number
            $issue_title = $issue_object.title
            $issue_labels = $issue_object.labels.name
            $issue_url = $issue_object.url
            $issue_created_at = $issue_object.created_at

            # Check if the issue has a 'type-repo_work' tag
            if ($issue_labels -contains "type-repo_work") {
              # If it does, ignore the issue and move on to the next one
              Write-Host "Ignoring issue $issue_number as it has 'type-repo_work' tag."
              continue
            }

            # Check if the issue has a 'blocker' tag
            if ($issue_labels -contains "blocker") {
              # If it does, add the 'out-tte' tag if it's not assigned after 3 minutes
              $time_threshold = (Get-Date).AddMinutes(-3)
              if ([DateTime]::Parse($issue_created_at) -lt $time_threshold) {
                gh issue label add $issue_number out-tte
                Write-Host "Added 'out-tte' tag to issue $issue_number ($issue_title) as it was unassigned for more than 3 minutes."
              } else {
                Write-Host "Skipping issue $issue_number ($issue_title) as it is still within the 3 minute threshold."
              }
            } else {
              # If it doesn't, add the 'non-blocker' tag if it's not assigned after 6 minutes
              # Also, add the 'blocker' tag if it doesn't have any tag yet
              $time_threshold = (Get-Date).AddMinutes(-6)
              if ([DateTime]::Parse($issue_created_at) -lt $time_threshold) {
                if ($issue_labels.Length -eq 0) {
                  gh issue label add $issue_number blocker
                  Write-Host "Added 'blocker' tag to issue $issue_number ($issue_title) as it didn't have any tag yet."
                } else {
                  gh issue label add $issue_number non-blocker
                  Write-Host "Added 'non-blocker' tag to issue $issue_number ($issue_title) as it was unassigned for more than 6 minutes and didn't have the 'blocker' tag."
                }
              } else {
                Write-Host "Skipping issue $issue_number ($issue_title) as it is still within the 6 minute threshold."
              }
            }
          }