name: Tag comments 

# Define the event that triggers the workflow
on:
  workflow_dispatch:
    # Run the workflow every hour

 
env:
  # Set the value of the GH_TOKEN environment variable to the token associated with the GitHub App used to run the workflow
  GH_TOKEN: ${{ github.token }}

# Define the job that the workflow will run
jobs:
  tag-issues:
    runs-on: ubuntu-latest
    
    # Allow the workflow to modify issues in the repository
    permissions:
      issues: write 
      contents: read

    steps:
      # Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Tag issues based on their labels, assignees, and creation time
      - name: Get and label comments without Area label
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh auth login --with-token <<< $GITHUB_TOKEN
          $comments = gh issue list --json 'number,title,labels' --jq '.[] | select( any(.labels[]; .name | test("^área-")) | not )'
          $comments | ForEach-Object {
            $comment = $_
            $number = $comment.number
            $title = $comment.title
            Write-Host "Issue without area label: $title"
            gh issue label $number --add "área-unknow"
          }

      