name: Tag comments 

# Define the event that triggers the workflow
on:
  workflow_dispatch:
    # Run the workflow every hour

 
env:
  # Set the value of the GH_TOKEN environment variable to the token associated with the GitHub App used to run the workflow
  GH_TOKEN: ${{ github.token }}

# Define the job that the workflow will run
jobs:
  tag-issues:
    runs-on: ubuntu-latest
    
    # Allow the workflow to modify issues in the repository
    permissions:
      issues: write 
      contents: read
      discussions: write

    steps:
      # Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Tag issues based on their labels, assignees, and creation time
     
      - name: Get Discussions without Area Label
        id: get-discussions
        run: |
          $query = @"
            query {
              repository(name: "$env:GITHUB_REPOSITORY", owner: "$env:GITHUB_REPOSITORY_OWNER") {
                discussions(first: 100) {
                  nodes {
                    id
                    title
                    labels(first: 100) {
                      nodes {
                        name
                      }
                    }
                  }
                }
              }
            }"@
            
          $discussions = gh api graphql -f query="$query" --jq '.data.repository.discussions.nodes'

          Write-Output "Discussions without 'área-*' label: $($discussions_without_label.Count)"
          Write-Output "Discussion titles:"
          foreach ($discussion in $discussions_without_label) {
            Write-Output "- $($discussion.title)"
          }
